# Generated by Django 5.2.6 on 2025-09-24 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExit',
            fields=[
                ('exit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_from_entry', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Plate',
            new_name='DetectedPlates',
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_exit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plates.carexit')),
            ],
        ),
        migrations.CreateModel(
            name='Rfidcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
