# Generated by Django 5.2.6 on 2025-09-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_carexit_rename_plate_detectedplates_reader_rfidcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidcard',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
