# Generated by Django 5.2.6 on 2025-09-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0003_alter_rfidcard_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidcard',
            name='user',
        ),
    ]
