# Generated by Django 5.2.6 on 2025-09-25 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0004_remove_rfidcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='card_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
