# Generated by Django 5.2.6 on 2025-09-25 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0005_rfidcard_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='reader_id',
        ),
        migrations.AddField(
            model_name='reader',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False),
        ),
    ]
