# Generated by Django 5.2.6 on 2025-09-25 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0006_remove_reader_reader_id_reader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
