# Generated by Django 5.2.6 on 2025-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0007_alter_reader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
